[[hazelcast-nodejs-client]]
= Hazelcast Node.js Client
:icon: font

Node.js Client for Hazelcast, using Hazelcast Open Client Protocol 1.0 for Hazelcast 3.6 and higher

NOTE: This project currently in active development.

https://gitter.im/hazelcast-incubator/hazelcast-nodejs-client?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge[image:https://badges.gitter.im/Join%20Chat.svg[Join the chat at https://gitter.im/hazelcast-incubator/hazelcast-nodejs-client]]

== Development

=== Build And Install `hazelcast-client` From Sources

. clone repo https://github.com/hazelcast/hazelcast-nodejs-client.git
. install global dependencies `npm install -g typescript typings`
. install dependencies `npm install`
. compile TypeScript `gulp compile`
. link package locally `npm link`

== Use Locally Installed Package

. `cd` to project directory
. use a locally linked module `npm link hazelcast-nodejs-client`
. follow <<usage>> example

== Test

=== Test prerequisites

* http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html[Java 6+]
* https://github.com/hazelcast/hazelcast-remote-controller[Hazelcast Remote Controller]
** https://github.com/hazelcast/hazelcast-remote-controller/blob/master/nodejs-controller/README.md[Follow README]
* run the tests
+
----
npm test
----

== Implemented Features

* Map
** Get
** Put
** Remove
* Distributed Object Listener
* Lifecycle Service
* Smart Client

[[usage]]
== Usage

.JavaScript Example
[source,javascript]
----
var HazelcastClient = require('hazelcast-client').Client;
var person = {
    firstName: "Joe",
    lastName: "Doe",
    age: 42
};
var map;
HazelcastClient.newHazelcastClient().then(function (hazelcastClient) {
    map = hazelcastClient.getMap("personMap");
    map.put(1, person).then(function (val) {
        // prints previous value for key `1`
        console.log(val);
    });
    map.get(1).then(function (value) {
        console.log(value);
    })
});
----

== Mail Group

Please join the mail group if you are interested in using or developing Hazelcast.

http://groups.google.com/group/hazelcast

=== License

Hazelcast is available under the Apache 2 License. Please see the http://docs.hazelcast.org/docs/latest/manual/html-single/hazelcast-documentation.html#license-questions[Licensing appendix] for more information.

=== Copyright

Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.

Visit http://www.hazelcast.com[www.hazelcast.com] for more info.
