/* tslint:disable:no-bitwise */
export class AtomicReference {
static ATOMICREFERENCE_APPLY = 0x0b01;
static ATOMICREFERENCE_ALTER = 0x0b02;
static ATOMICREFERENCE_ALTERANDGET = 0x0b03;
static ATOMICREFERENCE_GETANDALTER = 0x0b04;
static ATOMICREFERENCE_CONTAINS = 0x0b05;
static ATOMICREFERENCE_COMPAREANDSET = 0x0b06;
static ATOMICREFERENCE_GET = 0x0b08;
static ATOMICREFERENCE_SET = 0x0b09;
static ATOMICREFERENCE_CLEAR = 0x0b0a;
static ATOMICREFERENCE_GETANDSET = 0x0b0b;
static ATOMICREFERENCE_SETANDGET = 0x0b0c;
static ATOMICREFERENCE_ISNULL = 0x0b0d;
}