/*
 * Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Auto-generated by Hazelcast Client Protocol Code Generator.
 *
 * @generated Hazelcast Client Protocol Code Generator @f33179b
 * @see <a href="https://github.com/hazelcast/hazelcast-client-protocol">Protocol Generator</a>
 * DO NOT MODIFY. Changes to this file will be lost when the code is regenerated.
 */

/* eslint-disable max-len */
import {BitsUtil} from '../util/BitsUtil';
import {FixSizedTypesCodec} from './builtin/FixSizedTypesCodec';
import {ClientMessage, Frame, RESPONSE_BACKUP_ACKS_OFFSET, PARTITION_ID_OFFSET} from '../protocol/ClientMessage';
import {UUID} from '../core/UUID';
import {StringCodec} from './builtin/StringCodec';
import {ByteArrayCodec} from './builtin/ByteArrayCodec';
import {ListMultiFrameCodec} from './builtin/ListMultiFrameCodec';
import {AddressImpl} from '../core/Address';
import {AddressCodec} from './custom/AddressCodec';
import {CodecUtil} from './builtin/CodecUtil';
import {ListIntegerCodec} from './builtin/ListIntegerCodec';
import {MemberInfo} from '../core/MemberInfo';
import {MemberInfoCodec} from './custom/MemberInfoCodec';
import {EntryListUUIDListIntegerCodec} from './builtin/EntryListUUIDListIntegerCodec';
import {MapCodec} from './builtin/MapCodec';

// hex: 0x000200
const REQUEST_MESSAGE_TYPE = 512;
// hex: 0x000201
// RESPONSE_MESSAGE_TYPE = 513

const REQUEST_UUID_OFFSET = PARTITION_ID_OFFSET + BitsUtil.INT_SIZE_IN_BYTES;
const REQUEST_SERIALIZATION_VERSION_OFFSET = REQUEST_UUID_OFFSET + BitsUtil.UUID_SIZE_IN_BYTES;
const REQUEST_ROUTING_MODE_OFFSET = REQUEST_SERIALIZATION_VERSION_OFFSET + BitsUtil.BYTE_SIZE_IN_BYTES;
const REQUEST_CP_DIRECT_TO_LEADER_ROUTING_OFFSET = REQUEST_ROUTING_MODE_OFFSET + BitsUtil.BYTE_SIZE_IN_BYTES;
const REQUEST_INITIAL_FRAME_SIZE = REQUEST_CP_DIRECT_TO_LEADER_ROUTING_OFFSET + BitsUtil.BOOLEAN_SIZE_IN_BYTES;
const RESPONSE_STATUS_OFFSET = RESPONSE_BACKUP_ACKS_OFFSET + BitsUtil.BYTE_SIZE_IN_BYTES;
const RESPONSE_MEMBER_UUID_OFFSET = RESPONSE_STATUS_OFFSET + BitsUtil.BYTE_SIZE_IN_BYTES;
const RESPONSE_SERIALIZATION_VERSION_OFFSET = RESPONSE_MEMBER_UUID_OFFSET + BitsUtil.UUID_SIZE_IN_BYTES;
const RESPONSE_PARTITION_COUNT_OFFSET = RESPONSE_SERIALIZATION_VERSION_OFFSET + BitsUtil.BYTE_SIZE_IN_BYTES;
const RESPONSE_CLUSTER_ID_OFFSET = RESPONSE_PARTITION_COUNT_OFFSET + BitsUtil.INT_SIZE_IN_BYTES;
const RESPONSE_FAILOVER_SUPPORTED_OFFSET = RESPONSE_CLUSTER_ID_OFFSET + BitsUtil.UUID_SIZE_IN_BYTES;
const RESPONSE_MEMBER_LIST_VERSION_OFFSET = RESPONSE_FAILOVER_SUPPORTED_OFFSET + BitsUtil.BOOLEAN_SIZE_IN_BYTES;
const RESPONSE_PARTITION_LIST_VERSION_OFFSET = RESPONSE_MEMBER_LIST_VERSION_OFFSET + BitsUtil.INT_SIZE_IN_BYTES;

/** @internal */
export interface ClientAuthenticationCustomResponseParams {
    status: number;
    address: AddressImpl | null;
    memberUuid: UUID | null;
    serializationVersion: number;
    serverHazelcastVersion: string;
    partitionCount: number;
    clusterId: UUID;
    failoverSupported: boolean;
    tpcPorts: number[] | null;
    tpcToken: Buffer | null;
    memberListVersion: number;
    memberInfos: MemberInfo[] | null;
    partitionListVersion: number;
    partitions: Array<[UUID, number[]]> | null;
    keyValuePairs: Map<string, string>;
    isTpcPortsExists: boolean;
    isTpcTokenExists: boolean;
    isMemberListVersionExists: boolean;
    isMemberInfosExists: boolean;
    isPartitionListVersionExists: boolean;
    isPartitionsExists: boolean;
    isKeyValuePairsExists: boolean;
}

/** @internal */
export class ClientAuthenticationCustomCodec {
    static encodeRequest(clusterName: string, credentials: Buffer, uuid: UUID | null , clientType: string, serializationVersion: number, clientHazelcastVersion: string, clientName: string, labels: string[], routingMode: number, cpDirectToLeaderRouting: boolean): ClientMessage {
        const clientMessage = ClientMessage.createForEncode();
        clientMessage.setRetryable(true);

        const initialFrame = Frame.createInitialFrame(REQUEST_INITIAL_FRAME_SIZE);
        FixSizedTypesCodec.encodeUUID(initialFrame.content, REQUEST_UUID_OFFSET, uuid);
        FixSizedTypesCodec.encodeByte(initialFrame.content, REQUEST_SERIALIZATION_VERSION_OFFSET, serializationVersion);
        FixSizedTypesCodec.encodeByte(initialFrame.content, REQUEST_ROUTING_MODE_OFFSET, routingMode);
        FixSizedTypesCodec.encodeBoolean(initialFrame.content, REQUEST_CP_DIRECT_TO_LEADER_ROUTING_OFFSET, cpDirectToLeaderRouting);
        clientMessage.addFrame(initialFrame);
        clientMessage.setMessageType(REQUEST_MESSAGE_TYPE);
        clientMessage.setPartitionId(-1);

        StringCodec.encode(clientMessage, clusterName);
        ByteArrayCodec.encode(clientMessage, credentials);
        StringCodec.encode(clientMessage, clientType);
        StringCodec.encode(clientMessage, clientHazelcastVersion);
        StringCodec.encode(clientMessage, clientName);
        ListMultiFrameCodec.encode(clientMessage, labels, StringCodec.encode);
        return clientMessage;
    }

    static decodeResponse(clientMessage: ClientMessage): ClientAuthenticationCustomResponseParams {
        const initialFrame = clientMessage.nextFrame();

        const response = {} as ClientAuthenticationCustomResponseParams;
        response.status = FixSizedTypesCodec.decodeByte(initialFrame.content, RESPONSE_STATUS_OFFSET);
        response.memberUuid = FixSizedTypesCodec.decodeUUID(initialFrame.content, RESPONSE_MEMBER_UUID_OFFSET);
        response.serializationVersion = FixSizedTypesCodec.decodeByte(initialFrame.content, RESPONSE_SERIALIZATION_VERSION_OFFSET);
        response.partitionCount = FixSizedTypesCodec.decodeInt(initialFrame.content, RESPONSE_PARTITION_COUNT_OFFSET);
        response.clusterId = FixSizedTypesCodec.decodeUUID(initialFrame.content, RESPONSE_CLUSTER_ID_OFFSET);
        response.failoverSupported = FixSizedTypesCodec.decodeBoolean(initialFrame.content, RESPONSE_FAILOVER_SUPPORTED_OFFSET);
        if (initialFrame.content.length >= RESPONSE_MEMBER_LIST_VERSION_OFFSET + BitsUtil.INT_SIZE_IN_BYTES) {
            response.memberListVersion = FixSizedTypesCodec.decodeInt(initialFrame.content, RESPONSE_MEMBER_LIST_VERSION_OFFSET);
            response.isMemberListVersionExists = true;
        } else {
            response.isMemberListVersionExists = false;
        }
        if (initialFrame.content.length >= RESPONSE_PARTITION_LIST_VERSION_OFFSET + BitsUtil.INT_SIZE_IN_BYTES) {
            response.partitionListVersion = FixSizedTypesCodec.decodeInt(initialFrame.content, RESPONSE_PARTITION_LIST_VERSION_OFFSET);
            response.isPartitionListVersionExists = true;
        } else {
            response.isPartitionListVersionExists = false;
        }
        response.address = CodecUtil.decodeNullable(clientMessage, AddressCodec.decode);
        response.serverHazelcastVersion = StringCodec.decode(clientMessage);
        if (clientMessage.hasNextFrame()) {
            response.tpcPorts = CodecUtil.decodeNullable(clientMessage, ListIntegerCodec.decode);
            response.isTpcPortsExists = true;
        } else {
            response.isTpcPortsExists = false;
        }
        if (clientMessage.hasNextFrame()) {
            response.tpcToken = CodecUtil.decodeNullable(clientMessage, ByteArrayCodec.decode);
            response.isTpcTokenExists = true;
        } else {
            response.isTpcTokenExists = false;
        }
        if (clientMessage.hasNextFrame()) {
            response.memberInfos = ListMultiFrameCodec.decodeNullable(clientMessage, MemberInfoCodec.decode);
            response.isMemberInfosExists = true;
        } else {
            response.isMemberInfosExists = false;
        }
        if (clientMessage.hasNextFrame()) {
            response.partitions = CodecUtil.decodeNullable(clientMessage, EntryListUUIDListIntegerCodec.decode);
            response.isPartitionsExists = true;
        } else {
            response.isPartitionsExists = false;
        }
        if (clientMessage.hasNextFrame()) {
            response.keyValuePairs = MapCodec.decode(clientMessage, StringCodec.decode, StringCodec.decode);
            response.isKeyValuePairsExists = true;
        } else {
            response.isKeyValuePairsExists = false;
        }

        return response;
    }
}
