/* tslint:disable */

export class ClientMessageType {
    static CLIENT_AUTHENTICATION = 0x0002;
    static CLIENT_AUTHENTICATIONCUSTOM = 0x0003;
    static CLIENT_ADDMEMBERSHIPLISTENER = 0x0004;
    static CLIENT_CREATEPROXY = 0x0005;
    static CLIENT_DESTROYPROXY = 0x0006;
    static CLIENT_GETPARTITIONS = 0x0008;
    static CLIENT_REMOVEALLLISTENERS = 0x0009;
    static CLIENT_ADDPARTITIONLOSTLISTENER = 0x000a;
    static CLIENT_REMOVEPARTITIONLOSTLISTENER = 0x000b;
    static CLIENT_GETDISTRIBUTEDOBJECTS = 0x000c;
    static CLIENT_ADDDISTRIBUTEDOBJECTLISTENER = 0x000d;
    static CLIENT_REMOVEDISTRIBUTEDOBJECTLISTENER = 0x000e;
    static CLIENT_PING = 0x000f;
}
