/* tslint:disable */
export class ContinuousQueryMessageType {
    static CONTINUOUSQUERY_PUBLISHERCREATEWITHVALUE = 0x1801;
    static CONTINUOUSQUERY_PUBLISHERCREATE = 0x1802;
    static CONTINUOUSQUERY_MADEPUBLISHABLE = 0x1803;
    static CONTINUOUSQUERY_ADDLISTENER = 0x1804;
    static CONTINUOUSQUERY_SETREADCURSOR = 0x1805;
    static CONTINUOUSQUERY_DESTROYCACHE = 0x1806;
}
