/* tslint:disable */
export class DynamicConfigMessageType {
    static DYNAMICCONFIG_ADDMULTIMAPCONFIG = 0x1e01;
    static DYNAMICCONFIG_ADDRINGBUFFERCONFIG = 0x1e02;
    static DYNAMICCONFIG_ADDCARDINALITYESTIMATORCONFIG = 0x1e03;
    static DYNAMICCONFIG_ADDLOCKCONFIG = 0x1e04;
    static DYNAMICCONFIG_ADDLISTCONFIG = 0x1e05;
    static DYNAMICCONFIG_ADDSETCONFIG = 0x1e06;
    static DYNAMICCONFIG_ADDREPLICATEDMAPCONFIG = 0x1e07;
    static DYNAMICCONFIG_ADDTOPICCONFIG = 0x1e08;
    static DYNAMICCONFIG_ADDEXECUTORCONFIG = 0x1e09;
    static DYNAMICCONFIG_ADDDURABLEEXECUTORCONFIG = 0x1e0a;
    static DYNAMICCONFIG_ADDSCHEDULEDEXECUTORCONFIG = 0x1e0b;
    static DYNAMICCONFIG_ADDSEMAPHORECONFIG = 0x1e0c;
    static DYNAMICCONFIG_ADDQUEUECONFIG = 0x1e0d;
    static DYNAMICCONFIG_ADDMAPCONFIG = 0x1e0e;
    static DYNAMICCONFIG_ADDRELIABLETOPICCONFIG = 0x1e0f;
    static DYNAMICCONFIG_ADDCACHECONFIG = 0x1e10;
    static DYNAMICCONFIG_ADDEVENTJOURNALCONFIG = 0x1e11;
}
