/* tslint:disable:no-bitwise */
export class EnterpriseMap {
static ENTERPRISEMAP_PUBLISHERCREATEWITHVALUE = 0x1801;
static ENTERPRISEMAP_PUBLISHERCREATE = 0x1802;
static ENTERPRISEMAP_MADEPUBLISHABLE = 0x1803;
static ENTERPRISEMAP_ADDLISTENER = 0x1804;
static ENTERPRISEMAP_SETREADCURSOR = 0x1805;
static ENTERPRISEMAP_DESTROYCACHE = 0x1806;
}