/* tslint:disable */
export class ExecutorServiceMessageType {
    static EXECUTORSERVICE_SHUTDOWN = 0x0901;
    static EXECUTORSERVICE_ISSHUTDOWN = 0x0902;
    static EXECUTORSERVICE_CANCELONPARTITION = 0x0903;
    static EXECUTORSERVICE_CANCELONADDRESS = 0x0904;
    static EXECUTORSERVICE_SUBMITTOPARTITION = 0x0905;
    static EXECUTORSERVICE_SUBMITTOADDRESS = 0x0906;
}
