/* tslint:disable */
export class ScheduledExecutorMessageType {
    static SCHEDULEDEXECUTOR_SHUTDOWN = 0x1d01;
    static SCHEDULEDEXECUTOR_SUBMITTOPARTITION = 0x1d02;
    static SCHEDULEDEXECUTOR_SUBMITTOADDRESS = 0x1d03;
    static SCHEDULEDEXECUTOR_GETALLSCHEDULEDFUTURES = 0x1d04;
    static SCHEDULEDEXECUTOR_GETSTATSFROMPARTITION = 0x1d05;
    static SCHEDULEDEXECUTOR_GETSTATSFROMADDRESS = 0x1d06;
    static SCHEDULEDEXECUTOR_GETDELAYFROMPARTITION = 0x1d07;
    static SCHEDULEDEXECUTOR_GETDELAYFROMADDRESS = 0x1d08;
    static SCHEDULEDEXECUTOR_CANCELFROMPARTITION = 0x1d09;
    static SCHEDULEDEXECUTOR_CANCELFROMADDRESS = 0x1d0a;
    static SCHEDULEDEXECUTOR_ISCANCELLEDFROMPARTITION = 0x1d0b;
    static SCHEDULEDEXECUTOR_ISCANCELLEDFROMADDRESS = 0x1d0c;
    static SCHEDULEDEXECUTOR_ISDONEFROMPARTITION = 0x1d0d;
    static SCHEDULEDEXECUTOR_ISDONEFROMADDRESS = 0x1d0e;
    static SCHEDULEDEXECUTOR_GETRESULTFROMPARTITION = 0x1d0f;
    static SCHEDULEDEXECUTOR_GETRESULTFROMADDRESS = 0x1d10;
    static SCHEDULEDEXECUTOR_DISPOSEFROMPARTITION = 0x1d11;
    static SCHEDULEDEXECUTOR_DISPOSEFROMADDRESS = 0x1d12;
}
