/* tslint:disable:no-bitwise */
export class TransactionalQueue {
static TRANSACTIONALQUEUE_OFFER = 0x1401;
static TRANSACTIONALQUEUE_TAKE = 0x1402;
static TRANSACTIONALQUEUE_POLL = 0x1403;
static TRANSACTIONALQUEUE_PEEK = 0x1404;
static TRANSACTIONALQUEUE_SIZE = 0x1405;
}