/* tslint:disable */
export class TransactionalMultiMapMessageType {
    static TRANSACTIONALMULTIMAP_PUT = 0x1101;
    static TRANSACTIONALMULTIMAP_GET = 0x1102;
    static TRANSACTIONALMULTIMAP_REMOVE = 0x1103;
    static TRANSACTIONALMULTIMAP_REMOVEENTRY = 0x1104;
    static TRANSACTIONALMULTIMAP_VALUECOUNT = 0x1105;
    static TRANSACTIONALMULTIMAP_SIZE = 0x1106;
}
