/* tslint:disable */
export class TransactionalMapMessageType {
    static TRANSACTIONALMAP_CONTAINSKEY = 0x1001;
    static TRANSACTIONALMAP_GET = 0x1002;
    static TRANSACTIONALMAP_GETFORUPDATE = 0x1003;
    static TRANSACTIONALMAP_SIZE = 0x1004;
    static TRANSACTIONALMAP_ISEMPTY = 0x1005;
    static TRANSACTIONALMAP_PUT = 0x1006;
    static TRANSACTIONALMAP_SET = 0x1007;
    static TRANSACTIONALMAP_PUTIFABSENT = 0x1008;
    static TRANSACTIONALMAP_REPLACE = 0x1009;
    static TRANSACTIONALMAP_REPLACEIFSAME = 0x100a;
    static TRANSACTIONALMAP_REMOVE = 0x100b;
    static TRANSACTIONALMAP_DELETE = 0x100c;
    static TRANSACTIONALMAP_REMOVEIFSAME = 0x100d;
    static TRANSACTIONALMAP_KEYSET = 0x100e;
    static TRANSACTIONALMAP_KEYSETWITHPREDICATE = 0x100f;
    static TRANSACTIONALMAP_VALUES = 0x1010;
    static TRANSACTIONALMAP_VALUESWITHPREDICATE = 0x1011;
}
