/* tslint:disable */
export class XATransactionMessageType {
    static XATRANSACTION_CLEARREMOTE = 0x1601;
    static XATRANSACTION_COLLECTTRANSACTIONS = 0x1602;
    static XATRANSACTION_FINALIZE = 0x1603;
    static XATRANSACTION_COMMIT = 0x1604;
    static XATRANSACTION_CREATE = 0x1605;
    static XATRANSACTION_PREPARE = 0x1606;
    static XATRANSACTION_ROLLBACK = 0x1607;
}
