import {GenericRecord} from './GenericRecord';
import * as Long from 'long';
import {BigDecimal, LocalDate, LocalDateTime, LocalTime, OffsetDateTime} from '../../core';

export interface GenericRecordBuilder {
    compact(className: string): GenericRecordBuilder;
    build(): GenericRecord;
    setBoolean(fieldName: string, value: boolean): GenericRecordBuilder;
    setByte(fieldName: string, value: number): GenericRecordBuilder;
    setChar(fieldName: string, value: string): GenericRecordBuilder;
    setDouble(fieldName: string, value: number): GenericRecordBuilder;
    setFloat(fieldName: string, value: number): GenericRecordBuilder;
    setInt(fieldName: string, value: number): GenericRecordBuilder;
    setLong(fieldName: string, value: Long): GenericRecordBuilder;
    setShort(fieldName: string, value: number): GenericRecordBuilder;
    setString(fieldName: string, value: string | null): GenericRecordBuilder;
    setGenericRecord(fieldName: string, value: GenericRecord | null): GenericRecordBuilder;
    setDecimal(fieldName: string, value: BigDecimal | null): GenericRecordBuilder;
    setTime(fieldName: string, value: LocalTime | null): GenericRecordBuilder;
    setDate(fieldName: string, value: LocalDate | null): GenericRecordBuilder;
    setTimestamp(fieldName: string, value: LocalDateTime | null): GenericRecordBuilder;
    setTimestampWithTimezone(fieldName: string, value: OffsetDateTime | null): GenericRecordBuilder;
    setNullableBoolean(fieldName: string, value: boolean | null): GenericRecordBuilder;
    setNullableByte(fieldName: string, value: number | null): GenericRecordBuilder;
    setNullableShort(fieldName: string, value: number | null): GenericRecordBuilder;
    setNullableInt(fieldName: string, value: number | null): GenericRecordBuilder;
    setNullableLong(fieldName: string, value: Long | null): GenericRecordBuilder;
    setNullableFloat(fieldName: string, value: number | null): GenericRecordBuilder;
    setNullableDouble(fieldName: string, value: number | null): GenericRecordBuilder;
    setArrayOfBooleans(fieldName: string, value: boolean[] | null): GenericRecordBuilder;
    setArrayOfBytes(fieldName: string, value: number[] | null): GenericRecordBuilder;
    setArrayOfChars(fieldName: string, value: string[] | null): GenericRecordBuilder;
    setArrayOfFloats(fieldName: string, value: number[] | null): GenericRecordBuilder;
    setArrayOfInts(fieldName: string, value: number[] | null): GenericRecordBuilder;
    setArrayOfDoubles(fieldName: string, value: number[] | null): GenericRecordBuilder;
    setArrayOfLongs(fieldName: string, value: Long[] | null): GenericRecordBuilder;
    setArrayOfShorts(fieldName: string, value: number[] | null): GenericRecordBuilder;
    setArrayOfNullableBooleans(fieldName: string, value: (boolean | null)[] | null): GenericRecordBuilder;
    setArrayOfNullableBytes(fieldName: string, value: (number | null)[] | null): GenericRecordBuilder;
    setArrayOfNullableFloats(fieldName: string, value: (number | null)[] | null): GenericRecordBuilder;
    setArrayOfNullableInts(fieldName: string, value: (number | null)[] | null): GenericRecordBuilder;
    setArrayOfNullableDoubles(fieldName: string, value: (number | null)[] | null): GenericRecordBuilder;
    setArrayOfNullableLongs(fieldName: string, value: (Long | null)[] | null): GenericRecordBuilder;
    setArrayOfNullableShorts(fieldName: string, value: (number | null)[] | null): GenericRecordBuilder;
    setArrayOfStrings(fieldName: string, value: (string | null)[] | null): GenericRecordBuilder;
    setArrayOfDecimals(fieldName: string, value: (BigDecimal | null)[] | null): GenericRecordBuilder;
    setArrayOfTimes(fieldName: string, value: (LocalTime | null)[] | null): GenericRecordBuilder;
    setArrayOfDates(fieldName: string, value: (LocalDate | null)[] | null): GenericRecordBuilder;
    setArrayOfTimestamps(fieldName: string, value: (LocalDateTime | null)[] | null): GenericRecordBuilder;
    setArrayOfTimestampWithTimezones(fieldName: string, value: (OffsetDateTime | null)[] | null): GenericRecordBuilder;
    setArrayOfGenericRecords(fieldName: string, value: (GenericRecord | null)[] | null): GenericRecordBuilder;
}
