import {FieldKind} from './FieldKind';
import * as Long from 'long';
import {BigDecimal, LocalDate, LocalDateTime, LocalTime, OffsetDateTime} from '../../core';
import {Buffer} from 'buffer';
import {FieldBuilder} from './Field';

export abstract class GenericRecord {
    protected constructor(fields: { [name: string]: FieldBuilder<any> }) {
    }

    abstract getFieldNames(): Set<string>;
    abstract getFieldKind(fieldName: string): FieldKind;
    abstract hasField(fieldName: string): boolean;
    abstract getBoolean(fieldName: string): boolean;
    abstract getByte(fieldName: string): number;
    abstract getChar(fieldName: string): string;
    abstract getDouble(fieldName: string): number;
    abstract getFloat(fieldName: string): number;
    abstract getInt(fieldName: string): number;
    abstract getLong(fieldName: string): Long;
    abstract getShort(fieldName: string): number;
    abstract getString(fieldName: string): string;
    abstract getDecimal(fieldName: string): BigDecimal;
    abstract getTime(fieldName: string): LocalTime;
    abstract getDate(fieldName: string): LocalDate;
    abstract getTimestamp(fieldName: string): LocalDateTime;
    abstract getTimestampWithTimezone(fieldName: string): OffsetDateTime;
    abstract getGenericRecord(fieldName: string): GenericRecord;
    abstract getArrayOfBooleans(fieldName: string): boolean[];
    abstract getArrayOfBytes(fieldName: string): Buffer;
    abstract getArrayOfChars(fieldName: string): string[];
    abstract getArrayOfDoubles(fieldName: string): number[];
    abstract getArrayOfFloats(fieldName: string): number[];
    abstract getArrayOfInts(fieldName: string): number[];
    abstract getArrayOfLongs(fieldName: string): Long[];
    abstract getArrayOfShorts(fieldName: string): number[];
    abstract getArrayOfStrings(fieldName: string): string[];
    abstract getArrayOfDecimals(fieldName: string): BigDecimal[];
    abstract getArrayOfTimes(fieldName: string): LocalTime[];
    abstract getArrayOfDates(fieldName: string): LocalDate[];
    abstract getArrayOfTimestamps(fieldName: string): LocalDateTime[];
    abstract getArrayOfTimestampWithTimezones(fieldName: string): OffsetDateTime[];
    abstract getArrayOfGenericRecords(fieldName: string): GenericRecord[];
    abstract getNullableBoolean(fieldName: string): boolean | null;
    abstract getNullableByte(fieldName: string): number | null;
    abstract getNullableDouble(fieldName: string): number | null;
    abstract getNullableFloat(fieldName: string): number | null;
    abstract getNullableInt(fieldName: string): number | null;
    abstract getNullableLong(fieldName: string): Long | null;
    abstract getNullableShort(fieldName: string): number | null;
    abstract getArrayOfNullableBooleans(fieldName: string): (boolean | null)[];
    abstract getArrayOfNullableBytes(fieldName: string): (number | null)[];
    abstract getArrayOfNullableDoubles(fieldName: string): (number | null)[];
    abstract getArrayOfNullableFloats(fieldName: string): (number | null)[];
    abstract getArrayOfNullableInts(fieldName: string): (number | null)[];
    abstract getArrayOfNullableLongs(fieldName: string): (Long | null)[];
    abstract getArrayOfNullableShorts(fieldName: string): (number | null)[];
    abstract getBooleanFromArray(fieldName: string, index: number): boolean | null;
    abstract getByteFromArray(fieldName: string, index: number): number | null;
    abstract getCharFromArray(fieldName: string, index: number): string | null;
    abstract getShortFromArray(fieldName: string, index: number): number | null;
    abstract getIntFromArray(fieldName: string, index: number): number | null;
    abstract getLongFromArray(fieldName: string, index: number): Long | null;
    abstract getFloatFromArray(fieldName: string, index: number): number | null;
    abstract getDoubleFromArray(fieldName: string, index: number): number | null;
    abstract getStringFromArray(fieldName: string, index: number): string | null;
    abstract getGenericRecordFromArray(fieldName: string, index: number): GenericRecord | null;
    abstract getObjectFromArray<T>(fieldName: string, index: number): T | null;
    abstract getArrayOfObjects<T>(fieldName: string, componentType: new() => T): T[];
    abstract getObject<T>(fieldName: string): T;
    abstract getDecimalFromArray(fieldName: string, index: number): BigDecimal | null;
    abstract getTimeFromArray(fieldName: string, index: number): LocalTime | null;
    abstract getDateFromArray(fieldName: string, index: number): LocalDate | null;
    abstract getTimestampFromArray(fieldName: string, index: number): LocalDateTime | null;
    abstract getTimestampWithTimezoneFromArray(fieldName: string, index: number): OffsetDateTime | null;
    abstract getNullableBooleanFromArray(fieldName: string, index: number): boolean | null;
    abstract getNullableByteFromArray(fieldName: string, index: number): number | null;
    abstract getNullableShortFromArray(fieldName: string, index: number): number | null;
    abstract getNullableIntFromArray(fieldName: string, index: number): number | null;
    abstract getNullableLongFromArray(fieldName: string, index: number): Long | null;
    abstract getNullableFloatFromArray(fieldName: string, index: number): number | null;
    abstract getNullableDoubleFromArray(fieldName: string, index: number): number | null;
}
