import {FieldKind} from './FieldKind';
import * as Long from 'long';
import {BigDecimal, LocalDate, LocalDateTime, LocalTime, OffsetDateTime} from '../../core';
import {Buffer} from 'buffer';

export interface GenericRecord {
    getFieldNames(): Set<string>;
    getFieldKind(fieldName: string): FieldKind;
    hasField(fieldName: string): boolean;
    getBoolean(fieldName: string): boolean;
    getByte(fieldName: string): number;
    getChar(fieldName: string): string;
    getDouble(fieldName: string): number;
    getFloat(fieldName: string): number;
    getInt(fieldName: string): number;
    getLong(fieldName: string): Long;
    getShort(fieldName: string): number;
    getString(fieldName: string): string;
    getDecimal(fieldName: string): BigDecimal;
    getTime(fieldName: string): LocalTime;
    getDate(fieldName: string): LocalDate;
    getTimestamp(fieldName: string): LocalDateTime;
    getTimestampWithTimezone(fieldName: string): OffsetDateTime;
    getGenericRecord(fieldName: string): GenericRecord;
    getArrayOfBooleans(fieldName: string): boolean[];
    getArrayOfBytes(fieldName: string): Buffer;
    getArrayOfChars(fieldName: string): string[];
    getArrayOfDoubles(fieldName: string): number[];
    getArrayOfFloats(fieldName: string): number[];
    getArrayOfInts(fieldName: string): number[];
    getArrayOfLongs(fieldName: string): Long[];
    getArrayOfShorts(fieldName: string): number[];
    getArrayOfStrings(fieldName: string): string[];
    getArrayOfDecimals(fieldName: string): BigDecimal[];
    getArrayOfTimes(fieldName: string): LocalTime[];
    getArrayOfDates(fieldName: string): LocalDate[];
    getArrayOfTimestamps(fieldName: string): LocalDateTime[];
    getArrayOfTimestampWithTimezones(fieldName: string): OffsetDateTime[];
    getArrayOfGenericRecords(fieldName: string): GenericRecord[];
    getNullableBoolean(fieldName: string): boolean | null;
    getNullableByte(fieldName: string): number | null;
    getNullableDouble(fieldName: string): number | null;
    getNullableFloat(fieldName: string): number | null;
    getNullableInt(fieldName: string): number | null;
    getNullableLong(fieldName: string): Long | null;
    getNullableShort(fieldName: string): number | null;
    getArrayOfNullableBooleans(fieldName: string): (boolean | null)[];
    getArrayOfNullableBytes(fieldName: string): (number | null)[];
    getArrayOfNullableDoubles(fieldName: string): (number | null)[];
    getArrayOfNullableFloats(fieldName: string): (number | null)[];
    getArrayOfNullableInts(fieldName: string): (number | null)[];
    getArrayOfNullableLongs(fieldName: string): (Long | null)[];
    getArrayOfNullableShorts(fieldName: string): (number | null)[];
    getBooleanFromArray(fieldName: string, index: number): boolean | null;
    getByteFromArray(fieldName: string, index: number): number | null;
    getCharFromArray(fieldName: string, index: number): string | null;
    getShortFromArray(fieldName: string, index: number): number | null;
    getIntFromArray(fieldName: string, index: number): number | null;
    getLongFromArray(fieldName: string, index: number): Long | null;
    getFloatFromArray(fieldName: string, index: number): number | null;
    getDoubleFromArray(fieldName: string, index: number): number | null;
    getStringFromArray(fieldName: string, index: number): string | null;
    getGenericRecordFromArray(fieldName: string, index: number): GenericRecord | null;
    getObjectFromArray<T>(fieldName: string, index: number): T | null;
    getArrayOfObjects<T>(fieldName: string, componentType: new() => T): T[];
    getObject<T>(fieldName: string): T;
    getDecimalFromArray(fieldName: string, index: number): BigDecimal | null;
    getTimeFromArray(fieldName: string, index: number): LocalTime | null;
    getDateFromArray(fieldName: string, index: number): LocalDate | null;
    getTimestampFromArray(fieldName: string, index: number): LocalDateTime | null;
    getTimestampWithTimezoneFromArray(fieldName: string, index: number): OffsetDateTime | null;
    getNullableBooleanFromArray(fieldName: string, index: number): boolean | null;
    getNullableByteFromArray(fieldName: string, index: number): number | null;
    getNullableShortFromArray(fieldName: string, index: number): number | null;
    getNullableIntFromArray(fieldName: string, index: number): number | null;
    getNullableLongFromArray(fieldName: string, index: number): Long | null;
    getNullableFloatFromArray(fieldName: string, index: number): number | null;
    getNullableDoubleFromArray(fieldName: string, index: number): number | null;
}
