name: Get supported Node.js versions

on:
  workflow_call:
    outputs:
      node-versions:
        value: ${{ jobs.get-supported-node-versions.outputs.node-versions }}
      default-version:
        value: ${{ jobs.get-supported-node-versions.outputs.default-version }}

jobs:
  get-supported-node-versions:
    runs-on: ubuntu-latest
    outputs:
      node-versions: ${{ steps.get_versions.outputs.node-versions }}
      default-version: ${{ steps.get_versions.outputs.default-version }}
    steps:
      - name: Get supported Node.js versions
        id: get_versions
        run: |
          # Look for versions that are:
          # - Currently supported
          # - That are LTS
          # - Within LTS date range (i.e. not future LTS)
          NODE_VERSIONS=$(curl --silent https://raw.githubusercontent.com/nodejs/Release/main/schedule.json | jq --compact-output '
              def today: now | strftime("%Y-%m-%d");
              to_entries
              | map(select(.value.end > today and .value.lts != null and .value.lts < today))
              | [.[0].key, .[-1].key]
              | unique
          ')

          echo "node-versions=${NODE_VERSIONS}" >> ${GITHUB_OUTPUT}
          # Default to using the newest version
          echo "default-version=$(jq -r '.[1]' <<< ${NODE_VERSIONS})" >> ${GITHUB_OUTPUT}
