on: [pull_request]
name: Check links for markdown files
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruzickap/action-my-markdown-link-checker@v1
