name: Runs nightly tests on maintenance branches
on:
    workflow_dispatch:
    schedule:
        - cron: '0 2 */2 * *'
jobs:
    run-tests:
        runs-on: ${{ matrix.os }}
        name: Run tests of branch ${{ matrix.branch }} on ${{ matrix.os }} with Node ${{ matrix.nodejs_version }}
        strategy:
            matrix:
                branch: [ 5.0.x, 4.2.x, 4.1.x, 4.0.x ]
                os: [ ubuntu-latest, windows-latest ]
                nodejs_version: [ 10, 18 ]
            fail-fast: false
        steps:
            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  java-version: 8
                  distribution: temurin
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.nodejs_version }}
            - name: Disable line ending conversion of git
              if: ${{ matrix.os == 'windows-latest'}}
              run: git config --global core.autocrlf false
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ matrix.branch }}
            - name: Install dependencies and compile client
              run: |
                  npm install
                  npm run compile
            - name: Lint
              run: npm run lint
            - name: Validate User Code
              run: npm run validate-user-code
            - name: Run tests
              env:
                  HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
              run: npm run test
