name: Verify and publish a release candidate package
on:
    workflow_dispatch:
        inputs:
            branch_name:
                required: true
                description: The release's branch in the form '5.0.x'

jobs:
    verify-release-candidate-and-release:
        name: Verify release candidate and publish
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to branch ${{ github.event.inputs.branch_name }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.branch_name }}
            - name: Setup Java 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8
            - name: Setup Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - name: Download release candidate
              run: |
                  todo
                  todo
                  todo
            - name: Check integrity of the pack
              run: sha256sum --check release-pack.sha256
            - name: Unarchive the pack
              run: tar xvzf hazelcast-client-*.tgz
            - name: Install dependencies
              run: npm install
            - name: Replace lib folder
              run: |
                rm -rf lib
                mv release-pack-verification/package/lib .
            - name: Validate User Code
              run: npm run validate-user-code
            - name: Generate docs
              run: npm run generate-docs
            - name: Run all tests
              env:
                  HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
              run: npm run coverage
            - name: Congratulate
              run: |
                echo "Congratulations, the package has been released. Don't forget to tag the commit with a tag in the form 'v5.0.2'"
                echo "You can check the released package with `npm install hazelcast-client@released-version`"
