name: Upload Release Candidate and verify it
on:
    workflow_dispatch:
        inputs:
            commit_id:
                required: true
                description: Commit id to build the release pack from
                default: ''

jobs:
    pack-from-commit:
        name: Pack a release candidate archive from commit
        runs-on: ubuntu-latest

        if: ${{ github.event.inputs.commit_id != '' }}

        steps:
            - name: Checkout to commit ${{ github.event.inputs.commit_id }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.commit_id }}
            - name: Setup Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - name: Install dependencies
              run: npm install
            - name: Compile Typescript to JavaScript
              run: npm run compile
            - name: Pack an archive
              run: npm pack
            - name: Calculate sha256sum
              run: sha256sum hazelcast-client-*.tgz > release-pack.sha256
            - uses: actions/upload-artifact@v2
              with:
                  name: release-pack-${{ github.event.inputs.commit_id }}
                  path: hazelcast-client-*.tgz
            - uses: actions/upload-artifact@v2
              with:
                  name: release-pack-${{ github.event.inputs.commit_id }}
                  path: release-pack.sha256

    verify-uploaded-pack:
        name: Verify the uploaded pack
        runs-on: ubuntu-latest

        needs: pack-from-commit

        steps:
            - name: Checkout to commit ${{ github.event.inputs.commit_id }}
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.commit_id }}
            - name: Setup Node.js 12
              uses: actions/setup-node@v2
              with:
                  node-version: 12
            - uses: actions/download-artifact@v2
              with:
                  name: release-pack-${{ github.event.inputs.commit_id }}
                  path: /tmp/release-pack-verification
            - uses: actions/download-artifact@v2
              with:
                  name: release-pack-${{ github.event.inputs.commit_id }}
                  path: /tmp/release-pack-verification
            - name: Check integrity of the pack
              run: sha256sum --check release-pack.sha256
              working-directory: /tmp/release-pack-verification
            - name: Unarchive the pack
              run: tar xvzf hazelcast-client-*.tgz
              working-directory: /tmp/release-pack-verification
            - name: Setup Java 8
              uses: actions/setup-java@v1
              with:
                  java-version: 8
            - name: Install dependencies
              run: npm install
            - name: Move lib folder
              run: mv /tmp/release-pack-verification/package/lib .
            - name: Node version
              run: node -v
            - name: Validate User Code
              run: npm run validate-user-code
            - name: Generate docs
              run: npm run generate-docs
            - name: Run all tests
              env:
                  HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
              run: npm run coverage
            - name: Congratulate
              run: |
                echo "Congratulations, you can now start other release verification steps. The artifact will be retanined for 90 days. After you verify it, you can start the actual release workflow."
