name: Upload Release Candidate to S3 and verify it
on:
    release:
        types: [published]
jobs:
    a:
        name: asd
        runs-on: ubuntu-latest
        steps:
            - run: echo Hello
